# 사이트 공통 설정
# 배포 도메인 확정 후 BASE_URL 을 실제 도메인으로 변경하세요.
BASE_URL = "https://www.ganda-go.example.com"

BRAND = "간다 GO"
PHONE = "0508-202-4719"
PHONE_DISPLAY = "0508-202-4719"

# 상단 메뉴 — 하위 메뉴에는 키워드를 반복하지 않고 지역명·역명만 표시한다.
NAV = [
    ("홈", "/", []),
    ("동대문 출장마사지", "/massage/", [
        ("출장마사지 안내", "/massage/#service"),
        ("홈타이 안내", "/massage/#hometai"),
        ("전지역 방문 안내", "/massage/#coverage"),
        ("지하철역 인근 안내", "/massage/#stations"),
        ("예약 가능 시간", "/massage/#hours"),
        ("코스 선택 안내", "/massage/#course"),
        ("이용 전 확인사항", "/massage/#check"),
        ("위생·안전 안내", "/massage/#safety"),
        ("자주 묻는 질문", "/massage/#faq"),
    ]),
    ("지역별 안내", "/dongdaemun-gu/", [
        ("동대문구 전체", "/dongdaemun-gu/"),
        ("신설동", "/dongdaemun-gu/sinseol-dong/"),
        ("용두동", "/dongdaemun-gu/yongdu-dong/"),
        ("제기동", "/dongdaemun-gu/jegi-dong/"),
        ("전농동", "/dongdaemun-gu/jeonnong-dong/"),
        ("답십리동", "/dongdaemun-gu/dapsimni-dong/"),
        ("장안동", "/dongdaemun-gu/jangan-dong/"),
        ("청량리동", "/dongdaemun-gu/cheongnyangni-dong/"),
        ("회기동", "/dongdaemun-gu/hoegi-dong/"),
        ("휘경동", "/dongdaemun-gu/hwigyeong-dong/"),
        ("이문동", "/dongdaemun-gu/imun-dong/"),
    ]),
    ("지하철역별 안내", "/dongdaemun-gu/stations/", [
        ("역 전체", "/dongdaemun-gu/stations/"),
        ("신설동역", "/dongdaemun-gu/stations/sinseol-dong-station/"),
        ("용두역", "/dongdaemun-gu/stations/yongdu-station/"),
        ("제기동역", "/dongdaemun-gu/stations/jegi-dong-station/"),
        ("청량리역", "/dongdaemun-gu/stations/cheongnyangni-station/"),
        ("회기역", "/dongdaemun-gu/stations/hoegi-station/"),
        ("외대앞역", "/dongdaemun-gu/stations/hankuk-univ-foreign-studies-station/"),
        ("신이문역", "/dongdaemun-gu/stations/sinimun-station/"),
        ("답십리역", "/dongdaemun-gu/stations/dapsimni-station/"),
        ("장한평역", "/dongdaemun-gu/stations/janghanpyeong-station/"),
    ]),
    ("테마별 안내", "/themes/", [
        ("전체 테마", "/themes/"),
        ("스웨디시", "/themes/swedish/"),
        ("로미로미", "/themes/lomi-lomi/"),
        ("타이마사지", "/themes/thai-massage/"),
        ("중국마사지", "/themes/chinese-massage/"),
        ("아로마테라피", "/themes/aromatherapy/"),
        ("홈케어", "/themes/home-care/"),
        ("호텔식마사지", "/themes/hotel-style/"),
        ("발마사지", "/themes/foot-massage/"),
        ("스포츠·경락", "/themes/sports/"),
        ("스킨케어", "/themes/skin-care/"),
        ("왁싱", "/themes/waxing/"),
        ("커플 관리", "/themes/couple/"),
        ("24시간", "/themes/24-hours/"),
        ("수면 가능", "/themes/sleep-friendly/"),
    ]),
    ("코스안내", "/courses/", [
        ("전체 코스", "/courses/"),
        ("피로 회복 관리", "/courses/#recovery"),
        ("아로마 관리", "/courses/#aroma"),
        ("스포츠 관리", "/courses/#sports"),
        ("홈타이 코스", "/courses/#homethai"),
        ("커플·가족 방문 관리", "/courses/#family"),
        ("기업·단체 방문 관리", "/courses/#biz"),
        ("가격 안내", "/courses/#price"),
        ("코스 선택 가이드", "/courses/#howto"),
    ]),
    ("예약안내", "/reservation/", [
        ("예약 방법", "/reservation/#how"),
        ("예약 가능 시간", "/reservation/#hours"),
        ("방문 가능 장소", "/reservation/#where"),
        ("결제 안내", "/reservation/#payment"),
        ("변경·취소 안내", "/reservation/#change"),
        ("예약 전 체크사항", "/reservation/#checklist"),
    ]),
    ("이용가이드", "/guide/", [
        ("처음 이용하시는 분", "/guide/#first"),
        ("방문 전 준비사항", "/guide/#prepare"),
        ("위생 및 안전 기준", "/guide/#hygiene"),
        ("관리 후 주의사항", "/guide/#after"),
        ("금지행위 안내", "/guide/#rules"),
        ("이용 FAQ", "/guide/#faq"),
    ]),
    ("매거진", "/magazine/", [
        ("전체 글", "/magazine/"),
        ("마사지 비교 가이드", "/magazine/swedish-vs-thai/"),
        ("처음 이용 가이드", "/magazine/first-time-guide/"),
        ("수면과 마사지", "/magazine/sleep-and-massage/"),
        ("운동 후 회복", "/magazine/post-workout-timing/"),
        ("어깨·목 결림 관리", "/magazine/neck-shoulder-care/"),
        ("부모님 선물 가이드", "/magazine/parents-gift/"),
    ]),
    ("후기", "/reviews/", [
        ("전체 후기", "/reviews/"),
        ("지역별 후기", "/reviews/#region"),
        ("역세권 후기", "/reviews/#station"),
        ("후기 작성 안내", "/reviews/#write"),
    ]),
    ("고객센터", "/support/", [
        ("공지사항", "/support/#notice"),
        ("자주 묻는 질문", "/support/#faq"),
        ("1:1 문의", "/support/#contact"),
        ("제휴·기업 문의", "/support/#biz"),
        ("개인정보처리방침", "/support/privacy/"),
        ("이용약관", "/support/terms/"),
    ]),
]
